# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

name: PR build

# Controls when the workflow will run
on:
  # run pipeline on pull request
  pull_request:
    # types were added because check-blocking-labels ran on specific types only
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  # run pipeline on merge queue
  merge_group:
  # run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-PR-checks
  cancel-in-progress: true

env:
  skip_jobs_on_label_change: ${{ github.event.action != 'labeled' || github.event.action != 'unlabeled' }}

jobs:
  check-blocking-labels:
    runs-on: ubuntu-latest
    if: github.event.action != 'reopened'
    steps:
      - name: Get Labels
        run: echo "labels=${{ toJson(github.event.pull_request.labels.*.name) }}" >> $GITHUB_ENV

      - name: Debug Labels
        run: echo "$labels"

      - name: Check Blocking Labels
        uses: "./.github/workflows/check-blocking-labels.yml"
        with:
          labels: ${{ env.labels }}

  main:
    # labeled and unlabeled only concern check-blocking-labels
    if: ${{ env.skip_jobs_on_label_change }}
    uses: "./.github/workflows/main.yml"
    permissions:
      contents: write
    with:
      create_release: false

  check-code-quality:
    # labeled and unlabeled only concern check-blocking-labels
    if: ${{ env.skip_jobs_on_label_change }}
    uses: "./.github/workflows/check-code-quality.yml"

  reuse-compliance:
    # labeled and unlabeled only concern check-blocking-labels
    if: ${{ env.skip_jobs_on_label_change }}
    uses: "./.github/workflows/reuse-compliance.yml"

  clang-tidy:
    # labeled and unlabeled only concern check-blocking-labels
    if: ${{ env.skip_jobs_on_label_change }}
    uses: "./.github/workflows/clang-tidy.yml"
    with:
      target: "all power_grid_model_benchmark_cpp"

  citations:
    # labeled and unlabeled only concern check-blocking-labels
    if: ${{ env.skip_jobs_on_label_change }}
    uses: "./.github/workflows/citations.yml"
